### ISSUE TITLE
速度値と実行時間値の入力方法

### ISSUE THREAD

**Issue by Dai1678** [t-robop/ScriptRobotController#39]
現状、ただのEditTextなのでなんでも設定できてしまう
(キーボードレイアウトは数字入力で始まるように設定してある)
EditText以外の入力方法で良いのありますか

速度値の入力範囲は、0〜255
実行時間値の入力範囲は、決めてない(常識的な範囲内で 20秒までとか)

**Comment by Thiroaki** [comment]
直してfix/generateMultiDataにfushしました

**Comment by Dai1678** [comment]
該当コード、 @y-ogawara に消されてて草
速度値の入力はダイアログに置かない仕様にするかもなので、とりあえずまだ未対応のままにしとく

**Comment by y-ogawara** [comment]
ぜんぶかきなおした

**Comment by multiverse2011** [comment]
こちらもdoneですね
