### ISSUE TITLE
スリープ復帰後にデータが消える

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/ScriptRobotController#81]
スリープ後縦画面のロック画面が出たあとにデータが消える。
事象確認済み端末
- GalaxyS8
- Maze Alpha X
- Mi 5

おそらくロック画面で画面回転が起こった後にデータが消える。

**Comment by y-ogawara** [comment]
https://qiita.com/kobakei/items/5f38339dd6528fdc6b5d
これの2番かなぁ
