### ISSUE TITLE
要素を並べ替える時にフィードバックがほしい

### ISSUE THREAD

**Issue by y-ogawara** [t-robop/ScriptRobotController#82]
現在要素を長押しすると、なにもフィードバックがないため、移動状態になったかどうかが判別できない。
振動させるか、ブロックの色を変えるなど、やりたい

**Comment by VaioYuki** [comment]
#92 やりましたー確認お願いしますー

**Comment by multiverse2011** [comment]
良さげなのでmergeしました
@VaioYuki THX！
